server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.fleet.packages:
  - name: apm
    version: latest
xpack.fleet.agentPolicies:
  - name: Fleet Server (APM)
    id: fleet-server-apm
    is_default_fleet_server: true
    is_managed: false
    namespace: default
    package_policies:
      - name: APM policy
        package:
          name: apm
        inputs:
          - type: apm
            enabled: true
            vars:
              - name: host
                value: "apm-server:8200"
              - name: url
                value: "http://apm-server:8200"