receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
exporters:
  otlp/elastic:
    endpoint: http://apm-server:8200
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: collector:6666
    namespace: default
service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ otlp, otlp/elastic ]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlp/elastic]