entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        # cert: "/usr/share/data-prepper/root-ca.pem"
        # username: "admin"
        # password: "admin"
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        # cert: "/usr/share/data-prepper/root-ca.pem"
        # username: "admin"
        # password: "admin"
        index_type: trace-analytics-service-map
metrics-pipeline:
      source:
        otel_metrics_source:
          ssl: false
          authentication:
           unauthenticated: 
      processor:
        - otel_metrics_raw_processor:
      sink:
        - opensearch:
              hosts: ["http://opensearch:9200"]
              insecure: true
              # username: "username"
              # password: "password
              index: metrics-otel-v1-%{yyyy.MM.dd}
log-pipeline:
  source:
    http:
      ssl: false
      authentication:
        unauthenticated: 
      port: 2021
  processor:
    - grok:
        match:
          # This will match logs with a "log" key against the COMMONAPACHELOG pattern (ex: { "log": "actual apache log..." } )
          # You should change this to match what your logs look like. See the grok documenation to get started.
          log: [ "%{SYSLOGTIMESTAMP:timestamp} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource} %{SYSLOGPROG}:" ]
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        # username: "username"
        # password: "password
        index: apache_logs
    - stdout: